lang_small_published="Created:"
lang_small_updated="modified:"
lang_small_tags="tags:"
lang_small_sep="&mdash;"
lang_footer_sep="&mdash;"
lang_footer_show_all="show all posts"
lang_footer_show_email="show e-mail"
